# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e3d2dddab8345839ff7626282f1db0dc0df8df5ec63bf33ea05bfd65c2bd99839c2292fe69575724162a4495f9860ded7f2b3a77c1e02a7a78e842f957a6a19

test:
  secret_key_base: bf5b6b681e7101db4a2081e859d93721a558c4e9a6faa50a0b6fa20d7591e049fbd14caa0ef1a2279e9dae8778b2dfdd6fc368e0c77e34e1e049d9e07daddc4a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
